# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Oskar Wickström's Programming Blog"
email: oskar.wickstrom@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My name is Oskar and I'm into music, programming and open source software. My
  current programming project is The Oden Programming Language.
baseurl: ""
url: "https://owickstrom.github.io"
twitter_username: owickstrom
github_username:  owickstrom

# Build settings
markdown: kramdown

sass:
  style: compressed
