#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Func Da World"
email: oskar.wickstrom@gmail.com
description: >
  Where Oskar Wickström writes about functional programming, open source
  software, and other delightful things.
baseurl: ""
url: "https://wickstrom.tech"
twitter_username: owickstrom
github_username:  owickstrom

navigation:
  - text: Blog
    url: /archive.html
  - text: Projects
    url: /projects.html
  - text: Talks
    url: /talks.html
  - text: Work
    url: /work.html
  - text: About
    url: /about.html

# Build settings
markdown: Pandoc

sass:
  style: compressed

gems:
  - jekyll-sitemap
  - jekyll-pandoc

pandoc:
  extensions:
    highlight-style: pygments

plantuml:
  plantuml_jar: ../deps/plantuml.jar     # path to plantuml jar
  tmp_folder: generated
